# Generated by Django 4.2.28 on 2026-03-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
        ('payments', '0002_alter_donation_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('PLATFORM', 'Platform'), ('CASE', 'Case'), ('THANK_YOU', 'Thank You')], default='PLATFORM', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thank_you_donations', to='shelters.shelter'),
        ),
    ]
