# Generated by Django 4.2.28 on 2026-03-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_donation_donation_type_donation_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
