# Generated by Django 4.2.28 on 2026-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_approved_amount_case_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('AWAITING_APPROVAL', 'Awaiting approval'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20),
        ),
    ]
