# Generated by Django 4.2.28 on 2026-03-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='proof_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='proof_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
