# Generated by Django 4.2.28 on 2026-04-04 00:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_closed_at_case_processing_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='animal',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog')], default='CAT', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='animal_names',
            field=models.CharField(blank=True, help_text='Write all animal names you know, or give temporary names if needed.', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='animals_count',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, 'Others')], default=1),
        ),
        migrations.AddField(
            model_name='case',
            name='money_for',
            field=models.CharField(choices=[('FOOD', 'Food'), ('NEUTERING', 'Neutering'), ('SURGERY', 'Surgery'), ('URGENT_SURGERY', 'Urgent surgery'), ('PRESCRIPTION_FOOD', 'Vet prescription food'), ('OTHER_VET_SERVICE', 'Other vet service'), ('FLEA_TREATMENT', 'Flea treatment'), ('TRANSPORT', 'Transport expenses'), ('OTHER', 'Others')], default='FOOD', max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(help_text='Please provide as many details as possible about the animals, their condition, and how the requested funds will be used.', validators=[django.core.validators.MinLengthValidator(120, message='Please provide a detailed description.')]),
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.case')),
            ],
        ),
    ]
