# Generated by Django 4.2.28 on 2026-04-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_animal_case_animal_names_case_animals_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='money_for',
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(choices=[('FOOD', 'Food'), ('NEUTERING', 'Neutering'), ('SURGERY', 'Surgery'), ('URGENT_SURGERY', 'Urgent surgery'), ('PRESCRIPTION_FOOD', 'Vet prescription food'), ('OTHER_VET_SERVICE', 'Other vet service'), ('FLEA_TREATMENT', 'Flea treatment'), ('TRANSPORT', 'Transport expenses'), ('OTHER', 'Others')], default='FOOD', help_text='Please select what the requested funds are for.', max_length=30),
        ),
    ]
