# Generated by Django 4.2.28 on 2026-04-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_remove_case_money_for_alter_case_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='When admin approves an amount greater than 0, the case will move from OPEN to PROCESSING.', max_digits=10, null=True),
        ),
    ]
