# Generated by Django 4.2.28 on 2026-04-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_approved_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='payout_method',
            field=models.CharField(choices=[('BANK', 'Bank transfer'), ('PAYPAL', 'PayPal')], help_text='Select how funds will be sent (Bank transfer or PayPal).', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='payout_reference',
            field=models.CharField(help_text='Provide bank details or PayPal email.', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(choices=[('FOOD', 'Food'), ('NEUTERING', 'Neutering'), ('SURGERY', 'Surgery'), ('URGENT_SURGERY', 'Urgent surgery'), ('PRESCRIPTION_FOOD', 'Vet prescription food'), ('OTHER_VET_SERVICE', 'Other vet service'), ('FLEA_TREATMENT', 'Flea treatment'), ('TRANSPORT', 'Transport expenses'), ('OTHER', 'Others')], default='FOOD', max_length=30),
        ),
    ]
