# Generated by Django 4.2.28 on 2026-04-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_payout_method_alter_case_payout_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='animals_count',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, 'Other (please specify in description)')], default=1),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(choices=[('FOOD', 'Food'), ('NEUTERING', 'Neutering'), ('SURGERY', 'Surgery'), ('URGENT SURGERY', 'Urgent surgery'), ('PRESCRIPTION_FOOD', 'Vet prescription food'), ('OTHER VET SERVICE', 'Other vet service'), ('FLEA TREATMENT', 'Flea treatment'), ('TRANSPORT', 'Transport expenses'), ('OTHER', 'Other')], default='FOOD', max_length=30),
        ),
    ]
