# Generated by Django 4.2.28 on 2026-04-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
        ('cases', '0010_alter_case_animals_count_alter_case_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank transfer'), ('PAYPAL', 'PayPal')], default='', help_text='Select how funds will be sent (Bank transfer or PayPal).', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='payout_reference',
            field=models.CharField(blank=True, default='', help_text='Provide bank details or PayPal email.', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='shelters.shelter'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(choices=[('FOOD', 'Food'), ('NEUTERING', 'Neutering'), ('SURGERY', 'Surgery'), ('URGENT SURGERY', 'Urgent surgery'), ('PRESCRIPTION_FOOD', 'Vet prescription food'), ('OTHER_VET_SERVICE', 'Other vet service'), ('FLEA_TREATMENT', 'Flea treatment'), ('TRANSPORT', 'Transport expenses'), ('OTHER', 'Other')], default='FOOD', max_length=30),
        ),
    ]
