# Generated by Django 4.2.28 on 2026-04-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_alter_case_payout_method_alter_case_payout_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(choices=[('food', 'Food'), ('neutering', 'Neutering'), ('surgery', 'Surgery'), ('urgent_surgery', 'Urgent surgery'), ('prescription_food', 'Vet prescription food'), ('other_vet_service', 'Other vet service'), ('flea_treatment', 'Flea treatment'), ('transport', 'Transport expenses'), ('other', 'Other')], default='FOOD', max_length=30),
        ),
    ]
