# Generated by Django 4.2.28 on 2026-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_case_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(choices=[('FOOD', 'Food'), ('NEUTERING', 'Neutering'), ('SURGERY', 'Surgery'), ('URGENT SURGERY', 'Urgent surgery'), ('PRESCRIPTION_FOOD', 'Vet prescription food'), ('OTHER_VET_SERVICE', 'Other vet service'), ('FLEA_TREATMENT', 'Flea treatment'), ('TRANSPORT', 'Transport expenses'), ('OTHER', 'Other')], default='FOOD', max_length=30),
        ),
    ]
