# Generated by Django 4.2.28 on 2026-04-08 15:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_alter_case_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
