# Generated by Django 4.2.28 on 2026-04-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='social_link',
        ),
        migrations.AddField(
            model_name='shelter',
            name='social_link_1',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='social_link_2',
            field=models.URLField(default='https://example.com'),
        ),
    ]
