# Generated by Django 4.2.28 on 2026-04-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_remove_shelter_social_link_shelter_social_link_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shelters/'),
        ),
    ]
